### ISSUE TITLE
Can we borrow your NPM account l7?

### ISSUE THREAD

**Issue by xiaoiver** [satchmorun/mote#11]
Sorry to bother you...
We're developing a data visualization project called [l7](https://github.com/antvis/L7/tree/next). And we want to publish some packages such as `@l7/scene` `@l7/layers` to npm registry.
But it seems that account 'l7' has been used. Can we borrow your l7 account to do some publish work?

**Comment by satchmorun** [comment]
Absolutely, as the plans I had for that namespace never happened.

It turns out I can't just delete the org, so I've contacted NPM as per the
docs I found (https://docs.npmjs.com/deleting-an-org). As soon as I hear
from them, I'll let you know.

Best,
Arun

**Comment by satchmorun** [comment]
@xiaoiver if you send a request to npm asking for the l7 namespace to be transferred to you, it'll kick off the process (they'll then ask me to confirm that I'm ok with it, which I will).

**Comment by xiaoiver** [comment]
Thanks a lot~ I have sent an email to NPM.
